// AUTOGENERATED by tokens/build — do not edit by hand.

import NucleusTokens

private let fontTokens: [String: NucleusFont] = [
    "b1": .b1,
    "b2": .b2,
    "b3": .b3,
    "c1": .c1,
    "d1": .d1,
    "h1": .h1,
    "h2": .h2,
    "h3": .h3,
    "h4": .h4,
    "h5": .h5,
    "l1": .l1,
    "l2": .l2,
    "l3": .l3,
    "s1": .s1,
    "s2": .s2,
    "s3": .s3,
]

extension NucleusFont: TokenResolvable {
    /// Resolves a type-scoped typography token (bare id), e.g. `s3`.
    public static func resolve(token: String) -> NucleusFont? {
        guard let value = fontTokens[token] else {
            assertionFailure("unknown NucleusFont token: \(token)")
            return nil
        }
        return value
    }
}
