// This file is auto-generated. Do not edit manually.

public extension NucleusColor {
    static let accentAqua = NucleusColor(light: "3FDBED", dark: "72E5F4")
    static let accentBlue = NucleusColor(light: "007CFB", dark: "4B98FE")
    static let accentMagenta = NucleusColor(light: "D501FD", dark: "DC4CFF")
    static let accentOrange = NucleusColor(light: "FF6F0F", dark: "FF925D")
    static let accentPink = NucleusColor(light: "FA58A4", dark: "FD83B6")
    static let accentPurple = NucleusColor(light: "7D00FE", dark: "8D55FF")
    static let backgroundDisabled = NucleusColor(light: "F7F7F7", dark: "1F1F1F")
    static let backgroundInverse = NucleusColor(light: "1F1F1F", dark: "FFFFFF")
    static let backgroundPrimary = NucleusColor(light: "FFFFFF", dark: "000000")
    static let backgroundSecondary = NucleusColor(light: "F7F7F7", dark: "1F1F1F")
    static let backgroundTertiary = NucleusColor(light: "F1F1F1", dark: "3A3A3A")
    static let backgroundTransparent = NucleusColor(hex: "FFFFFF14")
    static let foregroundDisabled = NucleusColor(light: "B8B8B8", dark: "9C9C9C")
    static let foregroundInverse = NucleusColor(light: "FFFFFF", dark: "1F1F1F")
    static let foregroundPrimary = NucleusColor(light: "1F1F1F", dark: "FFFFFF")
    static let foregroundSecondary = NucleusColor(light: "7D7D7D", dark: "B8B8B8")
    static let foregroundTertiary = NucleusColor(light: "9C9C9C", dark: "7D7D7D")
    static let statusError = NucleusColor(light: "EA392A", dark: "FC614F")
    static let statusInfo = NucleusColor(light: "007CFB", dark: "4B98FE")
    static let statusNeutral = NucleusColor(light: "9C9C9C", dark: "B8B8B8")
    static let statusSuccess = NucleusColor(light: "00C230", dark: "5CCE62")
    static let statusWarning = NucleusColor(light: "FFAE00", dark: "FFBF5D")
    static let strokePrimary = NucleusColor(light: "1F1F1F", dark: "FFFFFF")
    static let strokeSecondary = NucleusColor(light: "F1F1F1", dark: "3A3A3A")
    static let strokeTertiary = NucleusColor(light: "F7F7F7", dark: "1F1F1F")
    static let strokeTransparent = NucleusColor(light: "00000014", dark: "FFFFFF1A")
    static let surfaceOverlay = NucleusColor(light: "00000066", dark: "000000B2")
    static let surfacePage = NucleusColor(light: "FFFFFF", dark: "000000")
}
