import Foundation

let outputPath = URL(fileURLWithPath: CommandLine.arguments[1])
let inputPaths = CommandLine.arguments.dropFirst(2).map { URL(fileURLWithPath: $0) }

let pattern = try NSRegularExpression(pattern: #"static let (\w+) = WLDColor"#)
var names: [String] = []

for inputPath in inputPaths {
    let contents = try String(contentsOf: inputPath, encoding: .utf8)
    let range = NSRange(contents.startIndex..., in: contents)
    let matches = pattern.matches(in: contents, range: range)

    for match in matches {
        guard let range = Range(match.range(at: 1), in: contents) else { continue }
        names.append(String(contents[range]))
    }
}

var output = """
// generated by GenerateColorBindings plugin — do not edit manually.

import SwiftUI
import UIKit

public extension SwiftUI.Color {

"""

for name in names {
    output += "    static let \(name) = WLDColor.\(name).color\n"
}

output += """
}

public extension ShapeStyle where Self == Color {

"""

for name in names {
    output += "    static var \(name): Color { WLDColor.\(name).color }\n"
}

output += """
}

public extension UIColor {

"""

for name in names {
    output += "    static let \(name) = WLDColor.\(name).uiColor\n"
}

output += "}\n"

try output.write(to: outputPath, atomically: true, encoding: .utf8)
