import type { TokenCatalog } from './resolver-shared.js';

/**
 * Web token-path constants generator.
 *
 * Emits a runtime CommonJS module (`token-paths.js`) plus literal-typed declarations
 * (`token-paths.d.ts`) exporting one frozen object per token family, keyed by descriptive
 * camelCase, value = the canonical path string. This is the source of truth the app-backend
 * SDUI library imports instead of hand-writing path literals — so the backend maintains no
 * mapping of its own.
 */

interface ConstObject {
  name: string;
  doc: string;
  entries: Array<{ key: string; value: string }>;
}

function constObjects(catalog: TokenCatalog): ConstObject[] {
  const objects: ConstObject[] = [
    {
      name: 'ColorTokens',
      doc: 'Semantic color token paths, e.g. `semantic.color.text.primary`.',
      entries: catalog.semanticColors.map((c) => ({ key: c.accessor, value: c.token })),
    },
    {
      name: 'PrimitiveColorTokens',
      doc: 'Primitive color token paths, e.g. `primitive.color.grey.900`.',
      entries: catalog.primitiveColors.map((c) => ({ key: c.accessor, value: c.token })),
    },
    {
      name: 'TypographyTokens',
      doc: 'Grouped typography token paths, e.g. `typography.subtitle.s3`.',
      entries: catalog.fonts.map((f) => ({ key: f.key, value: f.token })),
    },
    {
      name: 'ButtonTokens',
      doc: 'Button style token paths, e.g. `component.button.inverse.32`.',
      entries: catalog.buttons.map((b) => ({ key: b.accessor, value: b.token })),
    },
    {
      name: 'IconTokens',
      doc: 'Icon token paths, e.g. `icon.arrow-right.regular`.',
      entries: catalog.icons.map((i) => ({ key: i.key, value: i.token })),
    },
  ];
  return objects.map((object) => ({
    ...object,
    entries: [...object.entries].sort((a, b) => a.key.localeCompare(b.key)),
  }));
}

const HEADER = '// AUTOGENERATED by tokens/build — do not edit by hand.';

export function generateWebTokenPathsJs(catalog: TokenCatalog): string {
  const lines: string[] = [
    "'use strict';",
    HEADER,
    "Object.defineProperty(exports, '__esModule', { value: true });",
    '',
  ];
  for (const object of constObjects(catalog)) {
    lines.push(`exports.${object.name} = Object.freeze({`);
    for (const { key, value } of object.entries) {
      lines.push(`  ${key}: '${value}',`);
    }
    lines.push('});');
    lines.push('');
  }
  return lines.join('\n');
}

export function generateWebTokenPathsDts(catalog: TokenCatalog): string {
  const lines: string[] = [
    HEADER,
    '// Canonical Nucleus token-path constants — runtime values with literal types.',
    '',
  ];
  for (const object of constObjects(catalog)) {
    lines.push(`/** ${object.doc} */`);
    lines.push(`export declare const ${object.name}: {`);
    for (const { key, value } of object.entries) {
      lines.push(`  readonly ${key}: '${value}';`);
    }
    lines.push('};');
    lines.push('');
  }
  return lines.join('\n');
}
