import type { TokenCatalog } from './resolver-shared.js';

/**
 * iOS token resolver generator.
 *
 * Emits one `+TokenResolvable.swift` conformance per primitive type (color/font/button/icon),
 * each living in that type's own target so a consumer only pulls in what it imports — no
 * monolithic target that depends on every module. Each conforms to the `TokenResolvable`
 * protocol (hand-written in the zero-dependency `NucleusTokens` target). Forward-only; an
 * unknown token returns `nil` and trips `assertionFailure` in debug builds.
 *
 * Tokens are type-scoped (the resolver type implies the namespace): font `s3`, color
 * `text.primary`, button `inverse.32`, icon `name.variant`.
 */

const HEADER = '// AUTOGENERATED by tokens/build — do not edit by hand.';

interface Row {
  key: string;
  value: string;
}

function dictionary(name: string, type: string, rows: Row[]): string {
  const body = [...rows]
    .sort((a, b) => a.key.localeCompare(b.key))
    .map((row) => `    "${row.key}": ${row.value},`)
    .join('\n');
  return `private let ${name}: [String: ${type}] = [\n${body}\n]`;
}

function simpleResolvable(args: {
  type: string;
  mapName: string;
  rows: Row[];
  doc: string;
}): string {
  return `${HEADER}

import NucleusTokens

${dictionary(args.mapName, args.type, args.rows)}

extension ${args.type}: TokenResolvable {
    /// ${args.doc}
    public static func resolve(token: String) -> ${args.type}? {
        guard let value = ${args.mapName}[token] else {
            assertionFailure("unknown ${args.type} token: \\(token)")
            return nil
        }
        return value
    }
}
`;
}

export function generateIOSColorResolvable(catalog: TokenCatalog): string {
  const rows: Row[] = [...catalog.semanticColors, ...catalog.primitiveColors].map((c) => ({
    key: c.wireToken,
    value: `.${c.accessor}`,
  }));
  return simpleResolvable({
    type: 'NucleusColor',
    mapName: 'colorTokens',
    rows,
    doc: 'Resolves a type-scoped color token, e.g. `text.primary` or `grey.900`.',
  });
}

export function generateIOSFontResolvable(catalog: TokenCatalog): string {
  const rows: Row[] = catalog.fonts.map((f) => ({ key: f.wireToken, value: `.${f.wireToken}` }));
  return simpleResolvable({
    type: 'NucleusFont',
    mapName: 'fontTokens',
    rows,
    doc: 'Resolves a type-scoped typography token (bare id), e.g. `s3`.',
  });
}

export function generateIOSButtonResolvable(catalog: TokenCatalog): string {
  const rows: Row[] = catalog.buttons.map((b) => ({ key: b.wireToken, value: `.${b.accessor}` }));
  return simpleResolvable({
    type: 'NucleusButton',
    mapName: 'buttonTokens',
    rows,
    doc: 'Resolves a type-scoped button style token, e.g. `inverse.32`.',
  });
}

export function generateIOSIconResolvable(catalog: TokenCatalog): string {
  const names = dictionary(
    'iconTokens',
    'NucleusIcon.Symbol',
    catalog.iconNames.map((i) => ({ key: i.name, value: `.${i.swiftCase}` })),
  );
  const variants = dictionary(
    'variantTokens',
    'NucleusIcon.Variant',
    catalog.iconVariants.map((v) => ({ key: v, value: `.${v}` })),
  );
  return `${HEADER}

import NucleusTokens

${names}

${variants}

extension NucleusIcon: TokenResolvable {
    /// Resolves a type-scoped icon token \`name.variant\`, e.g. \`arrow-right.regular\`.
    public static func resolve(token: String) -> NucleusIcon? {
        let components = token.components(separatedBy: ".")
        guard components.count == 2 else {
            assertionFailure("NucleusIcon token must be \`name.variant\`: \\(token)")
            return nil
        }
        guard
            let symbol = iconTokens[components[0]],
            let variant = variantTokens[components[1]],
            symbol.availableVariants.contains(variant)
        else {
            assertionFailure("unknown NucleusIcon token: \\(token)")
            return nil
        }
        return NucleusIcon(symbol, variant: variant)
    }
}
`;
}
