import type { TokenCatalog } from './resolver-shared.js';

/**
 * Web token-path constants generator.
 *
 * Emits a runtime CommonJS module (`token-paths.js`) plus literal-typed declarations
 * (`token-paths.d.ts`) exporting one frozen object per token family, keyed by descriptive
 * camelCase, value = the type-scoped wire token (e.g. `text.primary`, `s3`, `inverse.32`,
 * `arrow-right.regular`). This is the source of truth the app-backend SDUI library imports
 * instead of hand-writing token literals — so the backend maintains no mapping of its own.
 */

interface ConstObject {
  name: string;
  doc: string;
  entries: Array<{ key: string; value: string }>;
}

function constObjects(catalog: TokenCatalog): ConstObject[] {
  const objects: ConstObject[] = [
    {
      name: 'ColorTokens',
      doc: 'Type-scoped semantic color tokens, e.g. `text.primary`.',
      entries: catalog.semanticColors.map((c) => ({ key: c.accessor, value: c.wireToken })),
    },
    {
      name: 'PrimitiveColorTokens',
      doc: 'Type-scoped primitive color tokens, e.g. `grey.900`.',
      entries: catalog.primitiveColors.map((c) => ({ key: c.accessor, value: c.wireToken })),
    },
    {
      name: 'TypographyTokens',
      doc: 'Type-scoped typography tokens (bare id), e.g. `s3`.',
      entries: catalog.fonts.map((f) => ({ key: f.key, value: f.wireToken })),
    },
    {
      name: 'ButtonTokens',
      doc: 'Type-scoped button style tokens, e.g. `inverse.32`.',
      entries: catalog.buttons.map((b) => ({ key: b.accessor, value: b.wireToken })),
    },
    {
      name: 'IconTokens',
      doc: 'Type-scoped icon tokens, e.g. `arrow-right.regular`.',
      entries: catalog.icons.map((i) => ({ key: i.key, value: i.wireToken })),
    },
  ];
  return objects.map((object) => ({
    ...object,
    entries: [...object.entries].sort((a, b) => a.key.localeCompare(b.key)),
  }));
}

const HEADER = '// AUTOGENERATED by tokens/build — do not edit by hand.';

export function generateWebTokenPathsJs(catalog: TokenCatalog): string {
  const lines: string[] = [
    "'use strict';",
    HEADER,
    "Object.defineProperty(exports, '__esModule', { value: true });",
    '',
  ];
  for (const object of constObjects(catalog)) {
    lines.push(`exports.${object.name} = Object.freeze({`);
    for (const { key, value } of object.entries) {
      lines.push(`  ${key}: '${value}',`);
    }
    lines.push('});');
    lines.push('');
  }
  return lines.join('\n');
}

export function generateWebTokenPathsDts(catalog: TokenCatalog): string {
  const lines: string[] = [
    HEADER,
    '// Canonical Nucleus token-path constants — runtime values with literal types.',
    '',
  ];
  for (const object of constObjects(catalog)) {
    lines.push(`/** ${object.doc} */`);
    lines.push(`export declare const ${object.name}: {`);
    for (const { key, value } of object.entries) {
      lines.push(`  readonly ${key}: '${value}';`);
    }
    lines.push('};');
    lines.push('');
  }
  return lines.join('\n');
}
