import type { TokenCatalog } from './resolver-shared.js';

/**
 * iOS token-path resolver generator.
 *
 * Emits `NucleusTokenResolver.swift` — a single enum with static `[String: Token]` lookup tables
 * mapping each canonical path to its compile-time Nucleus accessor. Forward-only (`string → token`);
 * returns `nil` for unknown paths so callers fall back + report the miss.
 */

interface Row {
  token: string;
  value: string;
}

function sortRows(rows: Row[]): Row[] {
  return [...rows].sort((a, b) => a.token.localeCompare(b.token));
}

function dictionary(name: string, type: string, rows: Row[]): string {
  const body = sortRows(rows)
    .map((row) => `        "${row.token}": ${row.value},`)
    .join('\n');
  return `    private static let ${name}: [String: ${type}] = [\n${body}\n    ]`;
}

export function generateIOSResolver(catalog: TokenCatalog): string {
  const colorRows: Row[] = [...catalog.semanticColors, ...catalog.primitiveColors].map(
    (c) => ({ token: c.token, value: `.${c.accessor}` }),
  );
  const fontRows: Row[] = catalog.fonts.map((f) => ({ token: f.token, value: `.${f.accessor}` }));
  const buttonRows: Row[] = catalog.buttons.map((b) => ({
    token: b.token,
    value: `.${b.accessor}`,
  }));
  const iconRows: Row[] = catalog.icons.map((i) => ({
    token: i.token,
    value: `(.${i.swiftCase}, .${i.variant})`,
  }));

  return `// AUTOGENERATED by tokens/build — do not edit by hand.

import NucleusButtons
import NucleusColors
import NucleusFonts
import NucleusIcons

/// Resolves a canonical Nucleus token-path string — as emitted by the backend SDUI wire contract —
/// to the corresponding compile-time Nucleus token. Forward-only; returns \`nil\` for an unknown
/// path so callers can fall back to a default and report the miss (server and client ship on
/// different cadences, so an unknown token is expected and must not crash).
public enum NucleusTokenResolver {
    /// Resolves a color token path, e.g. \`semantic.color.text.primary\`.
    public static func color(_ token: String) -> NucleusColor? { colors[token] }

    /// Resolves a typography token path, e.g. \`typography.subtitle.s3\`.
    public static func font(_ token: String) -> NucleusFont? { fonts[token] }

    /// Resolves a button style token path, e.g. \`component.button.inverse.32\`.
    public static func button(_ token: String) -> NucleusButton? { buttons[token] }

    /// Resolves an icon token path, e.g. \`icon.arrow-right.regular\`.
    public static func icon(_ token: String) -> (icon: NucleusIcon, variant: NucleusIcon.Variant)? {
        icons[token]
    }

${dictionary('colors', 'NucleusColor', colorRows)}

${dictionary('fonts', 'NucleusFont', fontRows)}

${dictionary('buttons', 'NucleusButton', buttonRows)}

${dictionary('icons', '(icon: NucleusIcon, variant: NucleusIcon.Variant)', iconRows)}
}
`;
}
