import { ANDROID_DRAWABLE_PREFIX } from './icons-android.js';
import type { TokenCatalog } from './resolver-shared.js';

/**
 * Android token resolver generator.
 *
 * Emits `NucleusTokenResolver.kt` — a single object (Android ships one artifact, so there's no
 * cross-module coupling to avoid) with `when`-based lookups mapping each type-scoped wire token to
 * its compile-time Nucleus accessor. Colors are theme-aware (`isDark`); icons resolve straight to a
 * `@DrawableRes` id (Android has no runtime icon `Variant` enum — variant availability is encoded in
 * the type system). Tokens are type-scoped: font `s3`, color `text.primary`, button `inverse.32`,
 * icon `name.variant`. Forward-only; returns null for unknown tokens so callers fall back + report.
 */

const PACKAGE_NAME = 'com.worldcoin.nucleus.tokens';

interface Branch {
  token: string;
  value: string;
}

function sortBranches(branches: Branch[]): Branch[] {
  return [...branches].sort((a, b) => a.token.localeCompare(b.token));
}

function whenBody(branches: Branch[], indent: string): string {
  return sortBranches(branches)
    .map((branch) => `${indent}"${branch.token}" -> ${branch.value}`)
    .join('\n');
}

export function generateAndroidResolver(catalog: TokenCatalog): string {
  // Colors are split into single-param colorLight/colorDark `when`s (kept short and ktlint-clean)
  // behind a one-line `color(token, isDark)` dispatcher; primitives resolve the same in both.
  const colorLightBranches: Branch[] = [
    ...catalog.semanticColors.map((c) => ({
      token: c.wireToken,
      value: `NucleusSemanticColorsLight.${c.accessor}`,
    })),
    ...catalog.primitiveColors.map((c) => ({
      token: c.wireToken,
      value: `NucleusPrimitiveColors.${c.accessor}`,
    })),
  ];
  const colorDarkBranches: Branch[] = [
    ...catalog.semanticColors.map((c) => ({
      token: c.wireToken,
      value: `NucleusSemanticColorsDark.${c.accessor}`,
    })),
    ...catalog.primitiveColors.map((c) => ({
      token: c.wireToken,
      value: `NucleusPrimitiveColors.${c.accessor}`,
    })),
  ];
  const fontBranches: Branch[] = catalog.fonts.map((f) => ({
    token: f.wireToken,
    value: `NucleusFonts.${f.wireToken}`,
  }));
  const buttonBranches: Branch[] = catalog.buttons.map((b) => ({
    token: b.wireToken,
    value: `NucleusButtons.${b.accessor}`,
  }));
  const iconBranches: Branch[] = catalog.icons.map((i) => ({
    token: i.wireToken,
    value: `R.drawable.${ANDROID_DRAWABLE_PREFIX}_${i.androidStem}_${i.variant}`,
  }));

  return `// AUTOGENERATED by tokens/build — do not edit by hand.

package ${PACKAGE_NAME}

import androidx.annotation.DrawableRes
import androidx.compose.ui.graphics.Color
import com.worldcoin.nucleus.R

/**
 * Resolves a canonical Nucleus token-path string — as emitted by the backend SDUI wire contract —
 * to the corresponding compile-time Nucleus token. Forward-only; returns null for an unknown path
 * so callers can fall back to a default and report the miss (server and client ship on different
 * cadences, so an unknown token is expected and must not crash).
 */
object NucleusTokenResolver {
    /** Resolves a color token path, e.g. \`semantic.color.text.primary\`, for the active theme. */
    fun color(
        token: String,
        isDark: Boolean,
    ): Color? = if (isDark) colorDark(token) else colorLight(token)

    /** Resolves a typography token, e.g. \`s3\`. */
    fun font(token: String): NucleusFontStyle? =
        when (token) {
${whenBody(fontBranches, '            ')}
            else -> null
        }

    /** Resolves a button style token path, e.g. \`component.button.inverse.32\`. */
    fun button(token: String): NucleusButtonStyle? =
        when (token) {
${whenBody(buttonBranches, '            ')}
            else -> null
        }

    /** Resolves an icon token path, e.g. \`icon.arrow-right.regular\`, to a drawable resource id. */
    @DrawableRes
    fun iconRes(token: String): Int? =
        when (token) {
${whenBody(iconBranches, '            ')}
            else -> null
        }

    private fun colorLight(token: String): Color? =
        when (token) {
${whenBody(colorLightBranches, '            ')}
            else -> null
        }

    private fun colorDark(token: String): Color? =
        when (token) {
${whenBody(colorDarkBranches, '            ')}
            else -> null
        }
}
`;
}
