import type { ColorLeaf, FontToken } from './loaders.js';

/**
 * Web TypeScript types generator.
 *
 * Emits literal-union types so consumers (e.g. the app-backend SDUI library) get
 * compile-time safety instead of `Record<string, string>` when referencing token
 * paths. The wire value for each token is its canonical path:
 *   - colors: the full definition path, e.g. `semantic.color.text.primary`
 *   - typography: a grouped path `typography.{category}.{id}`, where the category is
 *     derived from the font-token id prefix (UI Kit 5 grouping).
 */

const FONT_CATEGORY: Record<string, string> = {
  d: 'display',
  n: 'numeric',
  h: 'headline',
  s: 'subtitle',
  l: 'label',
  b: 'body',
  c: 'caption',
};

function typographyPath(token: FontToken): string {
  const category = FONT_CATEGORY[token.name[0]];
  if (!category) {
    throw new Error(
      `Cannot derive typography category for font token "${token.name}". ` +
        `Add a prefix mapping to FONT_CATEGORY.`,
    );
  }
  return `typography.${category}.${token.name}`;
}

function unionType(name: string, values: string[]): string {
  const members = [...new Set(values)].sort();
  if (members.length === 0) {
    return `export type ${name} = never;`;
  }
  return `export type ${name} =\n${members.map((v) => `  | '${v}'`).join('\n')};`;
}

export interface WebTypesInput {
  /** Combined primitive + semantic color leaves. */
  colorTokens: ColorLeaf[];
  fontTokens: FontToken[];
}

export function generateWebTypes({
  colorTokens,
  fontTokens,
}: WebTypesInput): string {
  const colorPaths = colorTokens.map((token) => token.path.join('.'));
  const typographyPaths = fontTokens.map(typographyPath);

  return [
    '// AUTOGENERATED by tokens/build — do not edit by hand.',
    '// Canonical Nucleus token paths as literal-union types.',
    '',
    '/** Canonical color token path, e.g. `semantic.color.text.primary`. */',
    unionType('ColorToken', colorPaths),
    '',
    '/** Grouped typography token path, e.g. `typography.headline.h1`. */',
    unionType('TypographyToken', typographyPaths),
    '',
    '/** Runtime token maps are published as JSON modules (camelCase keys → values). */',
    'declare const tokens: Record<string, string>;',
    'export default tokens;',
    '',
  ].join('\n');
}
