import { typographyTokenPath } from './shared.js';
import type { ColorLeaf, FontToken } from './loaders.js';

/**
 * Web TypeScript types generator.
 *
 * Emits literal-union types so consumers (e.g. the app-backend SDUI library) get
 * compile-time safety instead of `Record<string, string>` when referencing token
 * paths. The wire value for each token is its canonical path:
 *   - colors: the full definition path, e.g. `semantic.color.text.primary`
 *   - typography: a grouped path `typography.{category}.{id}` (UI Kit 4.0 grouping)
 *   - buttons: a combined path `component.button.{variant}.{size}`
 */

function unionType(name: string, values: string[]): string {
  const members = [...new Set(values)].sort();
  if (members.length === 0) {
    return `export type ${name} = never;`;
  }
  return `export type ${name} =\n${members.map((v) => `  | '${v}'`).join('\n')};`;
}

export interface WebTypesInput {
  /** Combined primitive + semantic color leaves. */
  colorTokens: ColorLeaf[];
  fontTokens: FontToken[];
  /** Combined button style token paths, e.g. `component.button.primary.48`. */
  buttonStyleTokens: string[];
}

export function generateWebTypes({
  colorTokens,
  fontTokens,
  buttonStyleTokens,
}: WebTypesInput): string {
  const colorPaths = colorTokens.map((token) => token.path.join('.'));
  const typographyPaths = fontTokens.map((token) =>
    typographyTokenPath(token.name),
  );

  return [
    '// AUTOGENERATED by tokens/build — do not edit by hand.',
    '// Canonical Nucleus token paths as literal-union types.',
    '',
    '/** Canonical color token path, e.g. `semantic.color.text.primary`. */',
    unionType('ColorToken', colorPaths),
    '',
    '/** Grouped typography token path, e.g. `typography.headline.h1`. */',
    unionType('TypographyToken', typographyPaths),
    '',
    '/** Combined button style token path, e.g. `component.button.primary.48`. */',
    unionType('ButtonStyleToken', buttonStyleTokens),
    '',
    '/** Runtime token maps are published as JSON modules (camelCase keys → values). */',
    'declare const tokens: Record<string, string>;',
    'export default tokens;',
    '',
  ].join('\n');
}
