/**
 * Web TypeScript types generator.
 *
 * Emits literal-union types so consumers (e.g. the app-backend SDUI library) get compile-time
 * safety instead of `Record<string, string>` when referencing tokens. The members are the
 * type-scoped wire tokens the backend emits and the resolvers key on (the same `wireToken` values
 * that drive `token-paths.{js,d.ts}`, so the union types and the runtime constants can never
 * diverge):
 *   - colors: `text.primary` (semantic) / `grey.900` (primitive)
 *   - typography: `s3`
 *   - buttons: `inverse.32`
 *   - icons: `arrow-right.regular`
 */

function unionType(name: string, values: string[]): string {
  const members = [...new Set(values)].sort();
  if (members.length === 0) {
    return `export type ${name} = never;`;
  }
  return `export type ${name} =\n${members.map((v) => `  | '${v}'`).join('\n')};`;
}

export interface WebTypesInput {
  /** Type-scoped color wire tokens (semantic + primitive). */
  colorTokens: string[];
  /** Type-scoped typography wire tokens (bare ids). */
  typographyTokens: string[];
  /** Type-scoped button style wire tokens. */
  buttonStyleTokens: string[];
  /** Type-scoped icon wire tokens. */
  iconTokens: string[];
}

export function generateWebTypes({
  colorTokens,
  typographyTokens,
  buttonStyleTokens,
  iconTokens,
}: WebTypesInput): string {
  return [
    '// AUTOGENERATED by tokens/build — do not edit by hand.',
    '// Type-scoped Nucleus wire tokens as literal-union types.',
    '',
    '/** Type-scoped color token, e.g. `text.primary`. */',
    unionType('ColorToken', colorTokens),
    '',
    '/** Type-scoped typography token (bare id), e.g. `s3`. */',
    unionType('TypographyToken', typographyTokens),
    '',
    '/** Type-scoped button style token, e.g. `inverse.32`. */',
    unionType('ButtonStyleToken', buttonStyleTokens),
    '',
    '/** Type-scoped icon token, e.g. `arrow-right.regular`. */',
    unionType('IconToken', iconTokens),
    '',
    '/** Runtime token maps are published as JSON modules (camelCase keys → values). */',
    'declare const tokens: Record<string, string>;',
    'export default tokens;',
    '',
  ].join('\n');
}
