#!/usr/bin/env swift

import Foundation

let outputPath = URL(fileURLWithPath: CommandLine.arguments[1])
let inputPaths = CommandLine.arguments.dropFirst(2).map { URL(fileURLWithPath: $0) }

let tokenPattern = try NSRegularExpression(pattern: #"static let (\w+) = WLDColor"#)

// names that conflict with UIKit/SwiftUI built-in color properties
let skippedNames: Set<String> = ["white", "black"]

var names: [String] = []

for inputPath in inputPaths {
    let contents = try String(contentsOf: inputPath, encoding: .utf8)
    let range = NSRange(contents.startIndex..., in: contents)
    let matches = tokenPattern.matches(in: contents, range: range)

    for match in matches {
        guard let nameRange = Range(match.range(at: 1), in: contents) else { continue }
        let name = String(contents[nameRange])
        guard !skippedNames.contains(name) else { continue }
        names.append(name)
    }
}

var output = """
// generated by GenerateColorBindings plugin — do not edit manually.

import SwiftUI
import UIKit

public extension SwiftUI.Color {

"""

for name in names {
    output += "    static let \(name) = WLDColor.\(name).color\n"
}

output += """
}

public extension ShapeStyle where Self == Color {

"""

for name in names {
    output += "    static var \(name): Color { WLDColor.\(name).color }\n"
}

output += """
}

public extension UIColor {

"""

for name in names {
    output += "    static let \(name) = WLDColor.\(name).uiColor\n"
}

output += "}\n"

try output.write(to: outputPath, atomically: true, encoding: .utf8)
