// AUTOGENERATED by tokens/build — do not edit by hand.

import NucleusTokens

private let buttonTokens: [String: NucleusButton] = [
    "disabled.32": .disabled32,
    "disabled.40": .disabled40,
    "disabled.48": .disabled48,
    "ghost.32": .ghost32,
    "ghost.40": .ghost40,
    "ghost.48": .ghost48,
    "inverse.32": .inverse32,
    "inverse.40": .inverse40,
    "inverse.48": .inverse48,
    "primary.32": .primary32,
    "primary.40": .primary40,
    "primary.48": .primary48,
    "secondary.32": .secondary32,
    "secondary.40": .secondary40,
    "secondary.48": .secondary48,
    "tertiary.32": .tertiary32,
    "tertiary.40": .tertiary40,
    "tertiary.48": .tertiary48,
]

extension NucleusButton: TokenResolvable {
    /// Resolves a type-scoped button style token, e.g. `inverse.32`.
    public static func resolve(token: String) -> NucleusButton? {
        guard let value = buttonTokens[token] else {
            assertionFailure("unknown NucleusButton token: \(token)")
            return nil
        }
        return value
    }
}
